export const ACTIVE_BOARD_NAME = 'ACTIVE_BOARD_NAME';
export const NEW_BOARD = 'NEW_BOARD';
export const NEW_LIST = 'NEW_LIST';
export const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const SET_TASK_STATUS = 'SET_TASK_STATUS';
export const DRAG_HAPPENED = 'DRAG_HAPPENED';
